FSM: "PDArm"

head:
  kp: [20, 20]
  kd: [4, 4]
  default_joint_pos: [0.0, 0.0]

waist:
  kp: [100]
  kd: [20]
  default_joint_pos: [0.0]

# RL
# leg:
#   kp: [250, 250, 250, 300, 30, 30]
#   kd: [25, 25, 25, 25, 2, 2]
#   default_joint_pos: [-0.0, 0.0, 0.0, 0.0, -0.0, 0.0,
#                       -0.0, 0.0, 0.0, 0.0, -0.0, 0.0]

# arm:
#   kp: [50, 50, 50, 50, 40, 40, 40]
#   kd: [2, 2, 2, 2, 2, 2, 2]
#   default_joint_pos: [0.2, 0.2, 0.0, -0.2, 0.0, 0.0, 0.0,
#                       0.2, -0.2, 0.0, -0.2, 0.0, 0.0, 0.0]

# MPC
leg:
  kp: [250, 250, 250, 300, 40, 40]
  kd: [20, 20, 25, 25, 2, 2]
  default_joint_pos: [-0.06, 0.0, 0.0, 0.25, -0.165, 0.0,
                      -0.06, 0.0, 0.0, 0.25, -0.165, 0.0]

arm:
  kp: [30, 30, 30, 30, 30, 30, 30]
  kd: [2, 2, 2, 2, 2, 2, 2]
  default_joint_pos: [0.5, 0.2, 0.0, -1.0, 0.0, 0.0, 0.0,
                      0.5, -0.2, 0.0, -1.0, 0.0, 0.0, 0.0]
